#! /bin/bash

set -x
set -euo pipefail

user="$USER"

password="password"

# # Allow GUI login for the user.
# sudo dseditgroup -o edit -a "$user" -t user com.apple.access_loginwindow

# Allow VNC connection for the user.
sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
    -configure -access -on -privs -all -users "$user"

env \
    VNC_USERNAME="$user" \
    VNC_PASSWORD="$password" \
    vncviewer \
	localhost &
vnc_viewer_pid=$!

# Wait until the session is registered.
user_id=$(id -u "$user")
while true; do
    sleep 1
    if sudo launchctl print gui/"$user_id" >/dev/null; then
        break
    fi
done

kill "$vnc_viewer_pid"
