#! /bin/bash

set -x
set -euo pipefail

repo_url="$REPO_URL"
user="$USER"
runner_name="$RUNNER_NAME"
pat="${RUNNER_CFG_PAT:-}"
token="${RUNNER_TOKEN:-}"
labels="$RUNNER_LABELS"

fullName="$user"
password="password"

wd=$(dirname "$0")

sudo sysadminctl \
    -addUser "$user" \
    -fullName "$fullName" \
    -password "$password"

runner_home="/Users/$user"

# Hide the user from the login window.
sudo dscl . create "$runner_home" IsHidden 1

# Allow ssh for the user.
sudo dseditgroup -o edit -a "$user" -t user com.apple.access_ssh

# Make the user an admin.
sudo dseditgroup -o edit -a "$user" -t user admin

"$wd"/enable-gui-session

sudo cp -R actions-runner "$runner_home"/
sudo chown -R "$user" "$runner_home"/actions-runner

sudo -u "$user" "$runner_home"/actions-runner/config.sh \
    --url "$repo_url" \
    ${pat:+--pat "$pat"} \
    ${token:+--token "$token"} \
    --name "$runner_name" \
    --labels "$labels" \
    --unattended \
    --replace

# Run the runner via ssh (important, running with sudo -u "$user" will not result in proper gui session).

expect="$HOME/$user-run.expect"
cat >"$expect" <<EOF
spawn ssh -o "StrictHostKeyChecking=no" "$user@localhost" env PATH="$PATH" "$runner_home/actions-runner/run.sh"
expect "Password:"
send "password\\n"
set timeout 30
expect "Restarting runner..."
expect "Listening for Jobs"
EOF

cat "$expect"

expect -f "$expect"
