#! /bin/bash

set -x
set -euo pipefail

repo="$REPO"
user="$USER"
runner_name="$RUNNER_NAME"
pat="$RUNNER_CFG_PAT"
labels="$RUNNER_LABELS"

fullName="$user"
password="password"

sudo sysadminctl \
    -addUser "$user" \
    -fullName "$fullName" \
    -password "$password"

runner_home="/Users/$user"

# Hide the user from the login window.
sudo dscl . create "$runner_home" IsHidden 1

# Allow ssh for the user.
sudo dseditgroup -o edit -a "$user" -t user com.apple.access_ssh

# Allow VNC connection for the user.
sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
    -configure -access -on -privs -all -users "$user"

# Make the user an admin.
sudo dseditgroup -o edit -a "$user" -t user admin

sudo cp -R actions-runner "$runner_home"/
sudo chown -R "$user" "$runner_home"/actions-runner

sudo -u "$user" "$runner_home"/actions-runner/config.sh \
    --url "https://github.com/$repo" \
    --pat "$pat" \
    --name "$runner_name" \
    --labels "$labels" \
    --unattended \
    --replace \
    --disableupdate

# Run the runner via ssh (important, running with sudo -u "$user" will not result in proper gui session).

expect=$(mktemp /tmp/expect.XXXXXX)
cat >"$expect" <<EOF
spawn ssh -o "StrictHostKeyChecking=no" "$user@localhost" env PATH="$PATH" "$runner_home/actions-runner/run.sh"
expect "Password:"
send "password\\n"
expect eof
EOF

cat "$expect"

expect -f "$expect"
